package com.smartkrishisahayak.service;

import com.smartkrishisahayak.dto.response.SafetyAssessment;
import com.smartkrishisahayak.entity.enums.PreferredLanguage;

/**
 * Service for agricultural query safety assessment, off-topic detection,
 * risk classification, and expert referral enforcement.
 */
public interface AgricultureSafetyService {

    /**
     * Evaluates incoming user query for safety, risk tier, and knowledge confidence.
     *
     * @param userQuery       the farmer's input message
     * @param language        the preferred language (EN, MR, HI)
     * @param verifiedContext the retrieved verified agriculture context (or null)
     * @return SafetyAssessment containing risk level, confidence, and referral guidance
     */
    SafetyAssessment evaluateQuery(String userQuery, PreferredLanguage language, String verifiedContext);

    /**
     * Inspects and post-processes the AI generated answer to ensure responsible guidance,
     * no hazardous unverified claims, and inclusion of expert referrals where needed.
     *
     * @param aiResponse the raw response generated by the AI
     * @param userQuery  the original user query
     * @param language   the preferred language
     * @param assessment the pre-generation safety assessment
     * @return sanitized and safe response text
     */
    String sanitizeAiResponse(String aiResponse, String userQuery, PreferredLanguage language, SafetyAssessment assessment);

    /**
     * Checks if the user query is clearly unrelated to agriculture (e.g. sports, coding, politics).
     *
     * @param userQuery the query to inspect
     * @return true if query is off-topic
     */
    boolean isOffTopic(String userQuery);

    /**
     * Returns a polite localized redirect message for off-topic queries.
     *
     * @param language the preferred language
     * @return localized redirect message
     */
    String getOffTopicResponse(PreferredLanguage language);

    /**
     * Returns a localized notice when no verified knowledge is available.
     *
     * @param language the preferred language
     * @return localized no-knowledge notice
     */
    String getUnsupportedKnowledgeResponse(PreferredLanguage language);

    /**
     * Returns a localized expert referral notice advising consultation with Krishi Seva Kendra / Agriculture Officers.
     *
     * @param language the preferred language
     * @return localized expert referral text
     */
    String getExpertReferralNotice(PreferredLanguage language);
}
